trigger: none

stages:
- stage: stage1
  jobs:
  - job: stage1part1
    pool:
      vmImage: 'ubuntu-latest'
      name: default
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: stage2
  dependsOn: stage1
  jobs:
  - job: stage2part2
    pool:
      vmImage: 'ubuntu-latest'
      name: default
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo 'Greetings from Charlotte!'
          echo 'Variable: $(variable1)'

- stage: stage3
  dependsOn: stage2
  jobs:
  - job: stage3job1
    pool:
      vmImage: 'ubuntu-latest'
      name: default

- stage: stage4
  dependsOn: stage1
  jobs:
  - job: stage4job1
    pool:
      vmImage: 'ubuntu-latest'
      name: default

- stage: stage5
  dependsOn:
  - stage4
  - stage5
  jobs:
  - job: stage5job1
